sudo: required
services:
  - docker
  
before_install: 
    - docker build -t vidyasagarpandikashala/docker-react -f Dockerfile.dev . 
script: 
  - docker run -e CI=true vidyasagarpandikashala/docker-react npm run test 